export const products = [
  // Oversized Tees
  {
    id: "prod_01",
    name: "Storm Weaver Oversized Tee",
    category: "Oversized Tees",
    price: 1899,
    imageUrl: "/collections/oversizedtees/1.png",
    description: "A clean, relaxed aesthetic",
    details: ["100% Cotton", "240 GSM", "Oversized Fit", "Pre-Shrunk"],
  },
  {
    id: "prod_02",
    name: "Predator Oversized Tee",
    category: "Oversized Tees",
    price: 1999,
    imageUrl: "/collections/oversizedtees/3.png",
    description: "Keep it simple with sneakers for an easy, laid-back outfit.",
    details: [
      "High-Quality Print",
      "Heavyweight Cotton",
      "Drop Shoulders",
      "Durable Stitching",
    ],
  },
  {
    id: "prod_03",
    name: "Anti-Perfect Oversized Tee",
    category: "Oversized Tees",
    price: 1799,
    imageUrl: "/collections/oversizedtees/2.png",
    description: "Coffee Beige",
    details: [
      "240 GSM Fabric",
      "Boxy Fit",
      "Minimalist Design",
      "Signature Color",
    ],
  },

  // Daily Tees
  {
    id: "prod_04",
    name: "Daily Tee - White",
    category: "Daily Tees",
    price: 1299,
    imageUrl: "/collections/dailytees/1.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "Everyday Comfort",
      "Lightweight Cotton",
      "Classic Fit",
      "Versatile Style",
    ],
  },
  {
    id: "prod_05",
    name: "Daily Tee - Black",
    category: "Daily Tees",
    price: 1299,
    imageUrl: "/collections/dailytees/2.jpg",
    description: "A clean, relaxed aesthetic",
    details: ["Breathable Fabric", "Modern Cut", "All-Day Wear", "Soft Feel"],
  },
  {
    id: "prod_06",
    name: "Daily Tee - Blue",
    category: "Daily Tees",
    price: 1299,
    imageUrl: "/collections/dailytees/3.jpg",
    description: "A clean, relaxed aesthetic",
    details: ["Smooth Texture", "Relaxed Shape", "Durable Fabric", "Soft Wash"],
  },

  // Tones Original
  {
    id: "prod_07",
    name: "Tones Original - Cream",
    category: "Tones Originals",
    price: 2199,
    imageUrl: "/collections/tonesoriginal/1.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "Signature Series",
      "Heavy Fabric",
      "Oversized Fit",
      "Tones Logo",
    ],
  },
  {
    id: "prod_08",
    name: "Tones Original - Black",
    category: "Tones Originals",
    price: 2199,
    imageUrl: "/collections/tonesoriginal/2.jpg",
    description: "A clean, relaxed aesthetic",
    details: ["Minimal Aesthetic", "Durable Print", "Crew Neck", "240 GSM"],
  },
  {
    id: "prod_09",
    name: "Tones Original - Olive",
    category: "Tones Originals",
    price: 2199,
    imageUrl: "/collections/tonesoriginal/3.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "Exclusive Color",
      "Soft Handfeel",
      "Timeless Fit",
      "Unisex Design",
    ],
  },

  // Shirts
  {
    id: "prod_10",
    name: "Classic Shirt - White",
    category: "Shirts",
    price: 2799,
    imageUrl: "/collections/shirts/1.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "100% Cotton",
      "Relaxed Fit",
      "Button Closure",
      "Soft Wash Finish",
    ],
  },
  {
    id: "prod_11",
    name: "Classic Shirt - Beige",
    category: "Shirts",
    price: 2799,
    imageUrl: "/collections/shirts/2.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "Everyday Style",
      "Custom Fit",
      "Collared Neckline",
      "Breathable Weave",
    ],
  },
  {
    id: "prod_12",
    name: "Classic Shirt - Blue",
    category: "Shirts",
    price: 2799,
    imageUrl: "/collections/shirts/3.jpg",
    description: "A clean, relaxed aesthetic",
    details: ["Premium Cotton", "Smooth Texture", "Boxy Fit", "Minimal Design"],
  },

  // Satin Shirts
  {
    id: "prod_13",
    name: "Satin Shirt - White",
    category: "Satin Shirts",
    price: 3299,
    imageUrl: "/collections/satinshirts/1.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "Smooth Satin Blend",
      "Elegant Sheen",
      "Button Front",
      "Formal & Casual",
    ],
  },
  {
    id: "prod_14",
    name: "Satin Shirt - Grey",
    category: "Satin Shirts",
    price: 3299,
    imageUrl: "/collections/satinshirts/2.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "Subtle Gloss",
      "Relaxed Drape",
      "Luxe Texture",
      "Lightweight Feel",
    ],
  },
  {
    id: "prod_15",
    name: "Satin Shirt - Black",
    category: "Satin Shirts",
    price: 3299,
    imageUrl: "/collections/satinshirts/3.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "Refined Look",
      "Formal Ready",
      "Comfort Collar",
      "Bold Silhouette",
    ],
  },

  // Chinos
  {
    id: "prod_16",
    name: "Chinos - Khaki",
    category: "Chinos",
    price: 2499,
    imageUrl: "/collections/chinos/1.jpg",
    description: "A clean, relaxed aesthetic",
    details: ["Slim Fit", "Cotton Blend", "Tapered Legs", "Elastic Waistband"],
  },
  {
    id: "prod_17",
    name: "Chinos - Navy",
    category: "Chinos",
    price: 2499,
    imageUrl: "/collections/chinos/2.jpg",
    description: "A clean, relaxed aesthetic",
    details: [
      "All-Day Comfort",
      "Stretch Fabric",
      "Minimal Stitching",
      "Breathable",
    ],
  },
  {
    id: "prod_18",
    name: "Chinos - Charcoal",
    category: "Chinos",
    price: 2499,
    imageUrl: "/collections/chinos/3.jpg",
    description: "A clean, relaxed aesthetic",
    details: ["Tailored Look", "Flexible Waist", "Refined Finish", "Urban Fit"],
  },

  // Accessories
  {
    id: "prod_19",
    name: "Accessories - Sling Bag",
    category: "Accessories",
    price: 1499,
    imageUrl: "/collections/accessories/1.png",
    description: "A clean, relaxed aesthetic",
    details: [
      "Utility Design",
      "Adjustable Strap",
      "Durable Zip",
      "Water Resistant",
    ],
  },
  {
    id: "prod_20",
    name: "Accessories - Cap",
    category: "Accessories",
    price: 999,
    imageUrl: "/collections/accessories/2.png",
    description: "A clean, relaxed aesthetic",
    details: [
      "Embroidered Logo",
      "Adjustable Back",
      "Breathable Panels",
      "Curved Brim",
    ],
  },
  {
    id: "prod_21",
    name: "Accessories - Tote Bag",
    category: "Accessories",
    price: 899,
    imageUrl: "/collections/accessories/3.png",
    description: "A clean, relaxed aesthetic",
    details: [
      "100% Cotton",
      "Spacious Interior",
      "Reinforced Handles",
      "Eco Friendly",
    ],
  },
];
